version: '3'
services:

  redis:
    image: redis:latest
    ports:
      - "36379:6379"
    networks:
      - net-web
    privileged: true
    volumes:
      - ./.docker/redis/data:/data                                     # data dir
      - ./.docker/redis/conf/redis.conf:/usr/local/redis/redis.conf    # Configuration file
      - ./.docker/redis/logs/redis.log:/usr/local/logs/redis.log       # logs file
    restart: always
    container_name: redis
    env_file: .env

  php:
    depends_on:
      - redis
    image: php:${PHP_VERSION}-bullseye
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "9000:9000"
    networks:
      - net-web
    privileged: true
    volumes:
      - .:/var/www
    restart: always
    container_name: php
    env_file: .env

  composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
      - .:/var/www
    working_dir: /var/www
    env_file: .env


networks:
  net-web:
